ALTER TABLE ensemble
DROP CONSTRAINT ensemble_name_key;

CREATE TABLE service (
  service_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name VARCHAR(4096) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
