version: '3.1'

services:
  db:
    image: timescale/timescaledb:latest-pg14
    restart: always
    environment:
      POSTGRES_DB: resource-manager
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      TZ: 'UTC'
      PGTZ: 'UTC'

    ports:
      - "5432:5432"
