version: '3.8'

volumes:
  prometheus-data: {}
  grafana-data: {}

services:
  db:
    image: timescale/timescaledb:latest-pg14
    restart: always
    environment:
      POSTGRES_DB: resource-manager
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      TZ: 'UTC'
      PGTZ: 'UTC'
    networks:
      - my-network
    ports:
      - "5432:5432"
  db-exporter:
    image: burningalchemist/sql_exporter:0.13
    restart: always
    volumes:
      - ./sql_exporter.yml:/sql_exporter.yml
    ports:
      - "9399:9399"
    networks:
      - my-network
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      # enable live reload of config
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - my-network
  grafana:
    image: grafana/grafana:10.2.2
    ports:
      - '3001:3000'
    volumes:
      - grafana-data:/var/lib/grafana
      - ../grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ../grafana/datasources:/etc/grafana/provisioning/datasources
    networks:
      - my-network
    environment:
      # security
      GF_SECURITY_ADMIN_EMAIL: admin@localhost
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SECURITY_ALLOW_EMBEDDING: true
      GF_SECURITY_COOKIE_SAMESITE: none
      # auth
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_NAME: apollo-rm
      GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
      # theming
      GF_USERS_DEFAULT_THEME: light
networks:
  my-network:
