global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'db-exporter'
    static_configs:
      - targets: ['db-exporter:9399']
