apiVersion: 1

datasources:
  - name: ResourceManagerDB
    type: postgres
    url: db:5432
    isDefault: true
    # update user data
    user: root
    secureJsonData:
      password: 'root'
    uid: RESOURCE_MANAGER_DB
    jsonData:
      database: resource-manager
      sslmode: 'disable' # disable/require/verify-ca/verify-full
      maxOpenConns: 100 # Grafana v5.4+
      maxIdleConns: 100 # Grafana v5.4+
      maxIdleConnsAuto: true # Grafana v9.5.1+
      connMaxLifetime: 14400 # Grafana v5.4+
      postgresVersion: 1400 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
      timescaledb: true
  - name: Prometheus
    type: prometheus
    access: proxy
    # Access mode - proxy (server in the UI) or direct (browser in the UI).
    url: http://victoria-metrics:8428
    uid: RESOURCE_MANAGER_PROM
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.44.0
      cacheLevel: 'Medium'
      disableRecordingRules: false
  - name: VictoriaMetrics
    # <string, required> Sets the data source type.
    type: victoriametrics-datasource
    # <string, required> Sets the access mode, either
    # proxy or direct (Server or Browser in the UI).
    # Some data sources are incompatible with any setting
    # but proxy (Server).
    access: proxy
    # <string> Sets default URL of the single node version of VictoriaMetrics
    url: http://victoria-metrics:8428
    # <string> Sets the pre-selected datasource for new panels.
    # You can set only one default data source per organization.
    isDefault: false
    uid: RESOURCE_MANAGER_VM
  - name: infinity
    type: yesoreyeram-infinity-datasource
    access: proxy
    isDefault: false
    uid: RESOURCE_MANAGER_INFINITY
