apiVersion: 1

datasources:
  - name: ResourceManagerDB
    type: postgres
    url: db:5432
    isDefault: true
    # update user data
    user: root
    secureJsonData:
      password: 'root'
    jsonData:
      database: resource-manager
      sslmode: 'disable' # disable/require/verify-ca/verify-full
      maxOpenConns: 100 # Grafana v5.4+
      maxIdleConns: 100 # Grafana v5.4+
      maxIdleConnsAuto: true # Grafana v9.5.1+
      connMaxLifetime: 14400 # Grafana v5.4+
      postgresVersion: 1400 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
      timescaledb: true
