# This file is responsible for the deployment of the RM backend.
# The deployment is split into a service of type LoadBalancer to enable
# external access to the api and a deployment that defines the container and volume mounts.
apiVersion: v1
kind: Service
metadata:
  name: rm-api
spec:
  type: LoadBalancer
  selector:
    app: rm-api
  ports:
    # The external port of the api
    - port: 8888
      targetPort: 8080
  externalIPs:
    # Swap with cluster ip
    - <cluster-IP>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rm-api
spec:
  # The amount of replicas
  replicas: 1
  selector:
    matchLabels:
      app: rm-api
  template:
    metadata:
      labels:
        app: rm-api
    spec:
      containers:
        - name: rm-api
          # Pull latest image
          image: matthigas/rm-api:latest
          imagePullPolicy: Always
          env:
            # The host url of the db
            - name: db_host
              value: rm-db-service
            # The port of the db
            - name: db_port
              value: "5433"
            # The login credentials for the db
            - name: db_user
              value: root
            - name: db_pw
              value: root
            # Retry policy for database operations
            - name: max_retries
              value: "5"
            - name: retry_delay_millis
              value: "1000"
            # The path of the build directory
            - name: build_directory
              value: build
            # The path on the host to the build directory
            - name: dind_directory
              value: "var/lib/apollo-rm/"
            # The persistence path for upload files
            - name: upload_persist_directory
              value: "build/upload"
            # The temp path for upload files
            - name: upload_temp_directory
              value: "build/upload/temp"
            # The maximum size of uploaded files in bytes
            - name: max_file_size
              value: "10000000"
            # The secret to use for the JWT
            - name: jwt_secret
              value: "todo-swap-with-real-secret"
            # The time until a newly created token expires
            - name: token_minutes_valid
              value: "10080"
            # The period of time between each validation performed on all existing ensembles in minutes
            - name: ensemble_validation_period
              value: "60"
            # The insecure registries that are accessed for openfaas and ec2 deployments
            - name: docker_insecure_registries
              value: "[]"
            # The k8s secrets that contain the kubeconfigs for all monitored k8s resources
            - name: kube_config_secrets_name
              value: "rm_kubeconfigs"
            # The path of the directory where the kube configs to access registered k8s resources are stored
            - name: kube_config_directory
              value: "build/kubeconfig"
            # The namespace where the kube config secrets are stored
            - name: kube_config_secrets_namespace
              value: "default"
            # The timeout of k8s api requests in seconds
            - name: kube_api_timeout_seconds
              value: "10"
            # The period of time between each monitoring run performed on all existing k8s resources in minutes
            - name: kube_monitoring_period
              value: "5"
            # The secrets that contain credentials to private repositories
            - name: kube_image_pull_secrets
              value: "[\"regcred\"]"
          resources:
            # The resource limits
            limits:
              memory: "1000Mi"
              cpu: "1.5"
          ports:
            # The internal port of the api
            - containerPort: 8080
          securityContext:
            # Necessary for docker-in-docker
            privileged: true
          volumeMounts:
            # The volume where all build data (terraform files, files to build images) is stored
            - name: rm-api-storage
              mountPath: /build
            # The path to the docker.sock used by docker-in-docker
            - name: dind-storage
              mountPath: /var/run/docker.sock
      volumes:
        - name: dind-storage
          hostPath:
            path: /var/run/docker.sock
        - name: rm-api-storage
          hostPath:
            path: /var/lib/apollo-rm/build
      # Define service account with cluster role binding
      serviceAccountName: <service-account>
