apiVersion: v1
kind: Service
metadata:
  name: rm-benchmark
spec:
  type: LoadBalancer
  selector:
    app: rm-benchmark
  ports:
    # The external port of the api
    - port: 8892
      targetPort: 8080
  externalIPs:
    # Swap with cluster ip
    - 138.232.66.177
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rm-benchmark
spec:
  # The amount of replicas
  replicas: 1
  selector:
    matchLabels:
      app: rm-benchmark
  template:
    metadata:
      labels:
        app: rm-benchmark
    spec:
      containers:
        - name: rm-benchmark
          # Pull latest image
          image: matthigas/rm-benchmark:0.0.1
          imagePullPolicy: Always
          resources:
            # The resource requests
            requests:
              memory: "500Mi"
              cpu: "2"
          ports:
            # The internal port of the api, must match api_port env variable
            - containerPort: 8080
          securityContext:
            # Necessary for docker-in-docker
            privileged: true
      serviceAccountName: <service-account>
