ALTER TABLE resource_type
    ALTER COLUMN type_id SET DATA TYPE BIGINT,
    ALTER COLUMN type_id DROP DEFAULT,
    ALTER COLUMN type_id ADD GENERATED ALWAYS AS IDENTITY;

ALTER TABLE resource
    ALTER COLUMN resource_id SET DATA TYPE BIGINT,
    ALTER COLUMN resource_id DROP DEFAULT,
    ALTER COLUMN resource_id ADD GENERATED ALWAYS AS IDENTITY,
    ALTER COLUMN resource_type SET DATA TYPE BIGINT;

ALTER TABLE metric
    ALTER COLUMN metric_id SET DATA TYPE BIGINT,
    ALTER COLUMN metric_id DROP DEFAULT,
    ALTER COLUMN metric_id ADD GENERATED ALWAYS AS IDENTITY;

ALTER TABLE metric_value
    ALTER COLUMN metric_value_id SET DATA TYPE BIGINT,
    ALTER COLUMN metric_value_id DROP DEFAULT,
    ALTER COLUMN metric_value_id ADD GENERATED ALWAYS AS IDENTITY,
    ALTER COLUMN resource_id SET DATA TYPE BIGINT,
    ALTER COLUMN metric_id SET DATA TYPE BIGINT;
