# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

# Note about adding a WF status badge: This Markdown example adds a status badge for a workflow with the name "Greet Everyone."
# The OWNER of the repository is the actions organization and the REPOSITORY name is hello-world.
# ![example workflow name](https://github.com/actions/hello-world/workflows/Greet%20Everyone/badge.svg)


name: Apollo-Tools RM CI Java Repository

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build-unittest-integrationtest:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build -x pmdMain -x pmdTest --stacktrace
      - name: Generate the test report
        run: ./gradlew jacocotestreport
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ./backend/build/reports/jacoco/test/jacocoTestReport.xml
      - name: Run codacy-analysis-cli
        uses: codacy/codacy-analysis-cli-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          max-allowed-issues: 10
#     - name: Run integration tests
#       run: |
#         curl -X POST https://api.github.com/repos/Apollo-Core/IntegrationTests/dispatches \
#         -H 'Accept: application/vnd.github.everest-preview+json' \
#         -u ${{ secrets.IT_ACCESS_TOKEN }} \
#         --data '{"event_type": "Push to '"$GITHUB_REPOSITORY"'", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
  
